const dummyData = [
  {
    id: 1,
    image: '/spacedog.jpeg',
    title: 'Lizard',
    FixPrice: '0.009',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User1',
    OwnedBy: 'John Doe',
    OwnedByUserAddress: '0x8f3...70da',
  },
  {
    id: 2,
    image: '/spacedog.jpeg',
    title: 'Another Item',
    FixPrice: '0.015',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User2',
    OwnedByUserAddress: '0x8f3...70da',
    OwnedBy: 'User3',
  },
  {
    id: 3,
    image: '/spacedog.jpeg',
    title: 'Third Item',
    FixPrice: '0.007',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User1',
    OwnedByUserAddress: '0x8f3...70da',
    OwnedBy: 'User1',
  },
  {
    id: 4,
    image: '/spacedog.jpeg',
    title: 'Fourth Item',
    FixPrice: '0.012',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User3',
    OwnedBy: 'John Doe',
    OwnedByUserAddress: '0x8f3...70da',
  },
  {
    id: 5,
    image: '/spacedog.jpeg',
    title: 'Fifth Item',
    FixPrice: '0.008',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User2',
    OwnedByUserAddress: '0x8f3...10da',
    OwnedBy: 'User3',
  },
  {
    id: 6,
    image: '/spacedog.jpeg',
    title: 'Sixth Item',
    FixPrice: '0.011',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User1',
    OwnedByUserAddress: '0x8f3...10da',
    OwnedBy: 'User1',
  },
  {
    id: 7,
    image: '/spacedog.jpeg',
    title: 'Seventh Item',
    FixPrice: '0.013',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User3',
    OwnedByUserAddress: '0x8f3...10da',
    OwnedBy: 'User1',
  },
  {
    id: 8,
    image: '/spacedog.jpeg',
    title: 'Eighth Item',
    FixPrice: '0.009',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User2',
    OwnedByUserAddress: '0x8f3...20da',
    OwnedBy: 'User3',
  },
  {
    id: 9,
    image: '/spacedog.jpeg',
    title: 'Ninth Item',
    FixPrice: '0.014',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User1',
    OwnedByUserAddress: '0x8f3...30da',
    OwnedBy: 'User1',
  },
  {
    id: 10,
    image: '/spacedog.jpeg',
    title: 'Tenth Item',
    FixPrice: '0.010',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User3',
    OwnedByUserAddress: '0x8f3...40da',
    OwnedBy: 'User2',
  },
  {
    id: 11,
    image: '/spacedog.jpeg',
    title: 'Tenth Item',
    FixPrice: '0.010',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User3',
    OwnedBy: 'John Doe',
    OwnedByUserAddress: '0x8f3...50da',
  },
  {
    id: 12,
    image: '/spacedog.jpeg',
    title: 'Tenth Item',
    FixPrice: '0.010',
    CreatedDate: '2023-08-23',
    CreatedBy: 'User3',
    OwnedByUserAddress: '0x8f3...60da',
    OwnedBy: 'John Doe',
  },
]

export default dummyData
