import { useState } from 'react'
import Head from 'next/head'
import axios from 'axios'
// import styles from '@/styles/Home.module.css'

export default function Home() {
  const [query, setQuery] = useState('')
  const [data, setData] = useState()

  const executeQuery = async (query) => {
    try {
      const response = await axios.post('/api/query', { query })
      let data = await response.data
      setData(data)
    } catch (err) {
      console.log(err)
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <textarea type="text" value={query} onChange={(e) => setQuery(e.target.value)} />
        <button onClick={() => executeQuery(query)}>Execute</button>
        <div>
          {data}
        </div>
      </main>
    </>
  )
}
